"""add_goal_value_lookup_tables

Revision ID: d707e75e22c9
Revises: 3b9295191a08
Create Date: 2025-10-14 22:35:28.662415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd707e75e22c9'
down_revision: Union[str, None] = '3b9295191a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_value_lookup',
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('score_diff', sa.Integer(), nullable=False),
    sa.Column('goal_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('minute', 'score_diff')
    )
    op.create_table('stats_calculation_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('total_goals_processed', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_calculation_metadata')
    op.drop_table('goal_value_lookup')
    # ### end Alembic commands ###
